
// CREATE test cases for GETTING all the available shoes from the database

// CREATE test cases for INSERTING a new shoe in the database FRIST...
    // CHECK if the shoe is not in the database THEN...
    // INSERT the shoe in the database

// CREATE test cases for DELETING a shoe from the database using a shoe id FIRST...
    // CHECK if the quantity is GREATER than 0 THEN... 
    // DELETE a shoe from the database


// CREATE test cases for a function that takes in a brand name AND...
        // RETURN all the shoes for a given brand

    // CREATE test cases for a function that takes in a size AND...
        // RETURN all the shoes for a given size

    // CREATE test cases for a function that takes in a brand and size as objects AND...
        // RETURN all the shoes for a given brand and size